name: Release

run-name: "Release @flows/${{ github.event.inputs.package }}@${{ github.event.inputs.type }}"

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Release type"
        required: true
        type: choice
        options:
          - canary
          - patch
          - minor
          - major
      package:
        description: "Package"
        required: true
        type: choice
        options:
          - react
          - react-components
          - js
          - js-components

permissions:
  id-token: write # Required for OIDC
  contents: write # Required to create GH releases

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: 906021
          private-key: ${{ secrets.FLOWS_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - run: git remote set-url origin https://flows-bot[bot]:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}
      - run: git config user.name "flows-bot[bot]"
      - run: git config user.email "170794745+flows-bot[bot]@users.noreply.github.com"
      - run: pnpm install
      - env:
          RELEASE_TYPE: ${{ github.event.inputs.type }}
          PACKAGE_NAME: ${{ github.event.inputs.package }}
        run: node scripts/release.js --release=$RELEASE_TYPE --package=$PACKAGE_NAME
